config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires do
    resources :comments
    resources :answeras
    resources :answerbs
    get 'user_posteds', on: :collection
    get 'user_answereds', on: :collection
    get 'user_favorites', on: :collection
  end

  root 'questionnaires#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :only => [:index, :show]
  resources :notifications, :only => [:index]
  resources :favorites


  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :questionnaire
  has_many :cmtnotifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comments_params)
    @comment.user_id = current_user.id
    @cmtnotification = @comment.cmtnotifications.build(user_id: @comment.questionnaire.user.id )
    #@questionnaire = @comment.questionnaire
    respond_to do |format|
      #binding.pry
      if @comment.save
        unless @comment.questionnaire.user.id == current_user.id
          push_when_create(@comment)
        end
        format.html { redirect_to questionnaires_path, notice: 'コメントが投稿されました。'}
        format.js { render :index }
      else
        format.html { redirect_to questionnaires_path, notice: 'コメント作成時にエラーが起きました。' }
      end
    end
  end

def edit
  @comment = Comment.find(params[:id])
  @questionnaire = @comment.questionnaire
  respond_to do |format|
    format.js {render :edit}
  end
end

def update
  @comment = Comment.find(params[:id])
  if @comment.update(comments_params)
    redirect_to questionnaire_path(@comment.questionnaire.id), notice: "コメントを更新しました。"
  else
    redirect_to questionnaire_path(@comment.questionnaire.id), notice: "コメントを更新できませんでした。"
  end
end

def destroy
  @comment = Comment.find(params[:id])
  @questionnaire = @comment.questionnaire
  if @comment.destroy
    @comments = @questionnaire.comments
    respond_to do |format|
      format.html { redirect_to questionnaire_path(@questionnaire), notice: 'コメントを削除しました。'}
      format.js { render :destroy }
    end
  else
    @comments = @questionnaire.comments
    redirect_to questionnaire_path(@questionnaire), notice: 'コメントの削除ができません。'
  end
end

  private

  def comments_params
    params.require(:comment).permit([:questionnaire_id, :body])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([questionnaire, comment], remote: true) do |f| %>
  <div class='input'>
    <div class='text'>
      <%= image_tag(profile_img_url(current_user), :class=>'avatar_in_text') %>
      <%= f.text_area :body, :placeholder=>'コメントする', class: 'form-control' %>
      <%= f.hidden_field :questionnaire_id, :value => questionnaire.id %>
    </div><!-- text -->
  </div>
  <div class='submit'>
    <%= f.submit 'コメントする', class:'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment_already| %>
  <div class='comment-one clearfix'　id="comment-<%= comment_already.id %>">
      <% if questionnaire.answering_a_users.include?(comment_already.user) %>
        <div class='photo float-left'>
      <% elsif questionnaire.answering_b_users.include?(comment_already.user) %>
        <div class='photo float-right'>
      <% else %>
        <div class='wrapper-notyet'>
          <div class='photo float-left'>
      <% end %>
        <p>
          <span data-toggle="tooltip" data-placement="top" title="<%= User.find(comment_already.user_id).name %>　さんのコメント">
            <%= image_tag(profile_img_url(User.find(comment_already.user_id)), :class=>'avatar_in_comment') %>
          </span>
        </p>
        <p>
          <% if questionnaire.answering_a_users.include?(comment_already.user) %>
              Aに回答
          <% elsif questionnaire.answering_b_users.include?(comment_already.user) %>
              Bに回答
          <% else %>
              未回答
          <% end %>
        </p>
      </div>
      <% if questionnaire.answering_a_users.include?(comment_already.user) %>
      <div class='content content-a float-left'>
      <% elsif questionnaire.answering_b_users.include?(comment_already.user) %>
      <div class='content content-b float-right'>
      <% else %>
      <div class='content content-notyet float-left'>
      <% end %>
          <p><%= comment_already.body %></p>
      </div>
      <% if current_user.id == comment_already.user.id %>
      <% if questionnaire.answering_a_users.include?(comment_already.user) %>
        <div class="icons float-left">
      <% elsif questionnaire.answering_b_users.include?(comment_already.user) %>
        <div class="icons float-right">
      <% else %>
        <div class="icons float-left">
      <% end %>
          <%= link_to edit_questionnaire_comment_path(comment_already.questionnaire, comment_already), remote: true do %>
          <span class="fa fa-pencil-square-o fa-lg"></span>
          <% end %>
          <%= link_to questionnaire_comment_path(comment_already.questionnaire, comment_already), method: :delete, data: { confirm: '本当に削除していいですか？' }, remote: true  do %>
          <span class="fa fa-trash-o fa-lg"></span>
          <% end %>
        </div>
        <% if questionnaire.answering_a_users.include?(comment_already.user) %>
        <% elsif questionnaire.answering_b_users.include?(comment_already.user) %>
        <% else %>
        </div>
        <% end %>
      <% end %>
  </div> <!-- div .comment-one -->
<% end %>

app/views/comments/destroy.js.erb
$("#comments_area-<%= @questionnaire.id %>").html("<%= j(render 'comments/index', { comments: @comments, questionnaire: @questionnaire }) %>")

app/views/comments/edit.js.erb
$("#comments_area-<%= @questionnaire.id %>").html("<%= j(render 'comments/form', { comment: @comment, questionnaire: @questionnaire }) %>");
$("#new_comment_area-<%= @questionnaire.id %>").html('');

app/views/comments/index.js.erb
$("#comments_area-<%=  @comment.questionnaire.id %>").html("<%= j(render 'comments/index', { comments: @comment.questionnaire.comments, questionnaire: @comment.questionnaire }) %>");
$("textarea").each(function(){
    $(this).val("");
});