config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires do
    resources :comments
    resources :answeras
    resources :answerbs
    get 'user_posteds', on: :collection
    get 'user_answereds', on: :collection
    get 'user_favorites', on: :collection
  end

  root 'questionnaires#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :only => [:index, :show]
  resources :notifications, :only => [:index]
  resources :favorites


  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記

  has_many :questionnaires, dependent: :destroy
  has_many :comments, dependent: :destroy

  #answer
  has_many :answeras, dependent: :destroy
  has_many :answerbs, dependent: :destroy
  has_many :answered_a_qs, :through => :answeras, :source => 'questionnaire'
  has_many :answered_b_qs, :through => :answerbs, :source => 'questionnaire'

 #通知
  has_many :ansnotifications, dependent: :destroy
  has_many :cmtnotifications, dependent: :destroy
  has_many :favnotifications, dependent: :destroy

  # favorites questionnaires
  has_many :favorites, dependent: :destroy
  has_many :favorite_qs, :through => :favorites, :source => 'questionnaire'

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

   def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
     user = User.find_by(provider: auth.provider, uid: auth.uid)

     unless user
       user = User.new(
           name:     auth.extra.raw_info.name,
           provider: auth.provider,
           uid:      auth.uid,
           email:    "#{auth.uid}-#{auth.provider}@example.com",
           image_url:   auth.info.image,
           password: Devise.friendly_token[0, 20]
       )
       user.skip_confirmation!
       user.save(validate: false)
     end
     user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end


  def self.create_unique_string
      SecureRandom.uuid
  end

  def answered_qs
    self.answered_a_qs + self.answered_b_qs
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @questionnaires = @user.questionnaires.order(:created_at)
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_show_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :avatar, :avatar_cache)
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorite_form.html.erb
<div id="favorite_form">
  <% if questionnaire.favored_users.include?(current_user) %>
    <%= form_for(questionnaire.favorites.find_by(user_id: current_user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "お気に入りを解除", class: "btn btn-default" %>
    <% end %>
<% else  %>
    <%= form_for(current_user.favorites.build(questionnaire_id: questionnaire.id), remote: true) do |f| %>
    <%= f.hidden_field :questionnaire_id, :value => questionnaire.id %>
      <!-- <%= f.submit "お気に入りに追加", class: "btn btn-large btn-primary" %>　-->
      <%= button_tag :type => "submit", :class =>"btn btn-large btn-primary" do %>
        <i class="fa fa-heart"></i>お気に入りに追加
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<section class='user-index'>
  <div class='container'>
    <% @users.each do |user| %>
        <div class='user'>
          <div class='photo'>
            <%= image_tag(profile_img_url(user)) %>
          </div>
          <div class='name'>
            <span><%= link_to user.name, user %>  さん</span>
          </div>
          <div class='user-static-1'>
            <% if user.questionnaires.length > 0 %>
              <%= link_to user_posteds_questionnaires_path(userid: user.id) do %>
                <p><i>投稿数</i></p>
                <h3><%= user.questionnaires.length %></h3>
              <% end %>
            <% else %>
              <p><i>投稿数</i></p>
              <h3><%= user.questionnaires.length %></h3>
            <% end %>
          </div>
          <div class='user-static-1'>
            <% if user.answered_qs.length > 0 %>
              <%= link_to user_answereds_questionnaires_path(userid: user.id) do %>
                <p><i>回答数</i></p>
                <h3><%= user.answered_qs.length %></h3>
              <% end %>
              <% else %>
                <p><i>回答数</i></p>
                <h3><%= user.answered_qs.length %></h3>
              <% end %>
          </div>
          <div class='user-static-1'>
            <% if user.favorites.length > 0 %>
            <%= link_to user_favorites_questionnaires_path(userid: user.id) do %>
              <p><i>お気に入り</i></p>
              <h3><%= user.favorites.length %></h3>
            <% end %>
            <% else %>
              <p><i>お気に入り</i></p>
              <h3><%= user.favorites.length %></h3>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class='user-show'>
  <div class='container'>
    <%= image_tag(profile_img_url(@user), :class=>'user-top-avatar') %>
    <h2><%= @user.name %> さん</h2>
    <hr>

    <% if current_user.id == @user.id %>
      <%= link_to :新規にアンケートを作成する, new_questionnaire_path, class: 'btn btn-primary' %>
    <% end %>
    <hr>

    <div class='user-static clearfix'>
      <div class='user-static-1'>
        <% if @user.questionnaires.length > 0 %>
          <%= link_to user_posteds_questionnaires_path(userid: @user.id) do %>
            <p><i>投稿数</i></p>
            <h3><%= @user.questionnaires.length %></h3>
          <% end %>
        <% else %>
          <p><i>投稿数</i></p>
          <h3><%= @user.questionnaires.length %></h3>
        <% end %>
      </div>
      <div class='user-static-1'>
        <% if @user.answered_qs.length > 0 %>
          <%= link_to user_answereds_questionnaires_path(userid: @user.id) do %>
            <p><i>回答数</i></p>
            <h3><%= @user.answered_qs.length %></h3>
          <% end %>
          <% else %>
            <p><i>回答数</i></p>
            <h3><%= @user.answered_qs.length %></h3>
          <% end %>
      </div>
      <div class='user-static-1'>
        <% if @user.favorites.length > 0 %>
        <%= link_to user_favorites_questionnaires_path(userid: @user.id) do %>
          <p><i>お気に入り</i></p>
          <h3><%= @user.favorites.length %></h3>
        <% end %>
        <% else %>
          <p><i>お気に入り</i></p>
          <h3><%= @user.favorites.length %></h3>
        <% end %>
      </div>
    </div>
    <hr>

    <% if current_user.id == @user.id %>
      <%= link_to :アカウント情報, edit_user_registration_path(@user),  class: 'btn btn-primary' %>
    <% end %>

    <hr>

    <% if user_signed_in? %>
      <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %></p>
    <% end %>
  </div>
</section>