config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires do
    resources :comments
    resources :answeras
    resources :answerbs
    get 'user_posteds', on: :collection
    get 'user_answereds', on: :collection
    get 'user_favorites', on: :collection
  end

  root 'questionnaires#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :only => [:index, :show]
  resources :notifications, :only => [:index]
  resources :favorites


  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  validates :body, presence: true
  validate :date_by_check
  validate :body_or_image_a
  validate :body_or_image_b

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :answeras, dependent: :destroy
  has_many :answerbs, dependent: :destroy
  has_many :answering_a_users, :through => :answeras, :source => 'user'
  has_many :answering_b_users, :through => :answerbs, :source => 'user'

  has_many :ansnotifications, dependent: :destroy
  has_many :favnotifications, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favored_users, :through => :favorites, :source => 'user'

  def date_by_check
    if date_by.present?
      errors.add(:date_by, "には未来の日付を設定してください。") unless
      Time.current < self.date_by
    end
  end

  def body_or_image_a
    if optiona_body.nil? && optiona_image.nil?
        errors.add("選択肢Aについて、本文か画像のどちらかが必要です。")
    end
  end

  def body_or_image_b
    if optionb_body.nil? && optionb_image.nil?
      errors.add("選択肢Bについて、本文か画像のどちらかが必要です。")
    end
  end

  def answering_users
    answering_a_users + answering_b_users
  end

  mount_uploader :qimage, QimageUploader #deviseの設定配下に追記
  mount_uploader :optiona_image, AimageUploader #deviseの設定配下に追記
  mount_uploader :optionb_image, BimageUploader #deviseの設定配下に追記

end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: [:show, :edit, :update, :destroy]

  def create
    @questionnaire = Questionnaire.new(questionnaires_params)
    if @questionnaire.save
      redirect_to questionnaires_path, notice: '新しいアンケートを公開しました！'
    else
      redirect_to new_questionnaire_path, alert: 'アンケートの作成に失敗しました。'
    end
  end

  def edit
    if @questionnaire.answeras.empty? && @questionnaire.answerbs.empty?
    else
      redirect_to new_questionnaire_path, notice: '回答者があったので新規作成をしてください。'
    end
  end

  def update
    if @questionnaire.update(questionnaires_params)
      redirect_to questionnaire_path(@questionnaire), notice: 'アンケートを更新しました！'
    else
      redirect_to questionnaire_path(@questionnaire), alert: 'アンケートを更新できませんでした。'
    end
  end

  def destroy
    if @questionnaire.destroy
      redirect_to questionnaires_path, notice: "アンケートを削除しました。"
    else
      redirect_to questionnaire_path(@questionnaire), notice: 'アンケートを削除できませんでした。'
    end
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def index
    @questionnaires = Questionnaire.all.order(created_at: :desc)
  end

  def user_posteds
    @user = User.find(params[:userid])
    @questionnaires = @user.questionnaires.order(created_at: :desc)
    render 'index'
  end

  def user_favorites
    @user = User.find(params[:userid])
    @questionnaires = @user.favorite_qs.order(created_at: :desc)
    render 'index'
  end

  def user_answereds
    @user = User.find(params[:userid])
    @questionnaires = @user.answered_qs.order(created_at: :desc)
    render 'index'
  end

  def show
    @comments = @questionnaire.comments.all
    @comment = @questionnaire.comments.build
    @answera = @questionnaire.answeras.build
    @answerb = @questionnaire.answerbs.build
    Cmtnotification.find(params[:cnotification_id]).update(read: true) if params[:cnotification_id]
    Ansnotification.find(params[:anotification_id]).update(answered: true) if params[:anotification_id]
    Favnotification.find(params[:fnotification_id]).update(read: true) if params[:fnotification_id]
  end

  def confirm
    @questionnaire = Questionnaire.new(questionnaires_params)
    #binding.pry
    render :new if @questionnaire.invalid?
  end

  private

  def questionnaires_params
      params.require(:questionnaire).permit([:body, :qimage, :qimage_cache, :date_by, :user_id, :optiona_body, :optiona_image, :optiona_image_cache, :optionb_body, :optionb_image, :optionb_image_cache])
  end

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
    #@picture = @questionnaire.pictures.first
  end

end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
  def choose_new_or_edit
      if action_name == 'new'
          questionnaires_path
      elsif action_name == 'edit'
          questionnaire_path
      end
  end

end

app/views/questionnaires/_form.html.erb
<%= form_for(questionnaire, url: choose_new_or_edit) do |f| %>
    <% if questionnaire.errors.any? %>
        <div id="error_explanation">
            <h2><%= questionnaire.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% questionnaire.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= f.label :アンケートの内容 %>
    <br>
    <p>
      <%= f.text_field :body, class: 'form-control new-questionnaire-body', placeholder: '質問文を入力してください。' %>
    </p>
    <hr>
    <p>
      <%= f.label :画像投稿 %>
      <br>
      <label><input type="radio" name="qimageToggle" id="qimageToggle1" value="" checked="checked" /> なし</label>
      <label><input type="radio" name="qimageToggle" id="qimageToggle2" value="" /> アップロード</label>
      <div id='questionnaire-image-selection' style='display: none;'>
        <%= f.file_field :qimage %>
        <%= f.hidden_field :qimage_cache %>
      </div>
    </p>
    <hr>
    <p>
      <%= f.label :回答期限 %>
      <br>
      <label><input type="radio" name="deadlineToggle" id="deadlineToggle1" value="" checked="checked" /> なし</label>
      <label><input type="radio" name="deadlineToggle" id="deadlineToggle2" value="" /> 設定</label>
      <div id='deadline' style='display: none;'>
        <%= f.text_field :date_by, class: 'form-control datetimepicker' %>
      </div>
    </p>
    <%= f.hidden_field :user_id,  :value => current_user.id %>
    <hr>

    <div class='options'>
      <h3>選択肢の作成</h3>
        <label><input type="radio" name="optionSelectMakeToggle" id="optionSelectMakeToggle1" value="" checked="checked" /> 規定の選択肢から選ぶ</label>
        <label><input type="radio" name="optionSelectMakeToggle" id="optionSelectMakeToggle2" value="" /> オリジナルの選択肢を作成する</label>
        <div class='select-options'>
        <p>
          <label><input type="radio" name="optionSelectToggle" id="optionSelectToggle1" value="" checked="checked" />
            <div class='option-a container-child col-md-6 col-sm-12'>
              <%= f.label :A %> ：はい
            </div>
            <div class='option-b container-child col-md-6 col-sm-12'>
              <%= f.label :B %> ：いいえ
            </div>
          </label>
        </p>
        <p>
          <label><input type="radio" name="optionSelectToggle" id="optionSelectToggle2" value="" />
            <div class='option-a container-child col-md-6 col-sm-12'>
              <%= f.label :A %> ：行く
            </div>
            <div class='option-b container-child col-md-6 col-sm-12'>
              <%= f.label :B %> ：行かない
            </div>
          </label>
        </p>
        <p>
          <label><input type="radio" name="optionSelectToggle" id="optionSelectToggle3" value="" />
            <div class='option-a container-child col-md-6 col-sm-12'>
              <%= f.label :A %> ：好き
            </div>
            <div class='option-b container-child col-md-6 col-sm-12'>
              <%= f.label :B %> ：嫌い
            </div>
          </label>
        </p>
        </div>
        <div class='make-options' style='display: none;'>
          <div class='option-a container-child col-md-6 col-sm-12'>
            <%= f.label :A %>
            <p>
              <%= f.text_field :optiona_body, class: 'form-control', placeholder: '選択肢Aを入力してください' %>
            </p>
            <p>
              <%= f.file_field :optiona_image %>
              <%= f.hidden_field :optiona_image_cache %>
            </p>
          </div>
          <div class='option-b container-child col-md-6 col-sm-12'>
          <p>
            <%= f.label :B %>
            <%= f.text_field :optionb_body, class: 'form-control', placeholder: '選択肢Bを入力してください' %>
          </p>
          <p>
            <%= f.file_field :optionb_image %>
            <%= f.hidden_field :optionb_image_cache %>
          </p>
        </div>
      </div>
    </div>
    <input type='button' value='投稿' class='btn btn-primary btn-block' id='new-questionnaire-commit'>
    <!--
      <input type='submit' name='commit' value='投稿' class='btn btn-primary btn-block' id='new-questionnaire-commit' data-disable-with='投稿'>
    -->
<% end %>

app/views/questionnaires/confirm.html.erb
<h1>Questionnaires#confirm</h1>
<p>Find me in app/views/questionnaires/confirm.html.erb</p>

app/views/questionnaires/create.html.erb
<h1>Questionnaires#create</h1>
<p>Find me in app/views/questionnaires/create.html.erb</p>

app/views/questionnaires/destroy.html.erb
<h1>Questionnaires#destroy</h1>
<p>Find me in app/views/questionnaires/destroy.html.erb</p>

app/views/questionnaires/edit.html.erb
<div class="container">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 new-questionnaire">
    <h2>アンケートを編集する</h2>
        <%= render 'form', {questionnaire: @questionnaire} %>
    </div>
</div>

app/views/questionnaires/index.html.erb
<div id='new-questionnaire-btn' class='new-questionnaire-btn'>
    <p>
      <%= link_to new_questionnaire_path, class: 'in-new-questionnaire-btn' do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
      <% end %>
    </p>
</div>

<section class='questionnaire-index'>
  <div class='container'>
    <% @questionnaires.each do |questionnaire| %>
      <%= link_to questionnaire_path(questionnaire) do %>
        <div class='container-child col-md-12 col-sm-12 col-xs-12 questionnaire-1'>
          <div class='questionnaire-header clearfix'>
            <div class='user-info'>
              <%= image_tag(profile_img_url(questionnaire.user)) %>
              <%= questionnaire.user.name %>さんから
            </div>
            <div class='questionnaire-static-1'>
              <p><i>回答期限</i></p>
              <% if questionnaire.date_by? %>
                <p><%= questionnaire.date_by.strftime("%Y/%m/%d/ %H:%M") %></p>
              <% elsif %>
                <p>なし</p>
              <% end %>
            </div>
          </div>

          <div class='questionnaire-body clearfix'>
            <i class="fa fa-quora" aria-hidden="true"></i>
            <%= questionnaire.body %>
            <% if questionnaire.qimage? %>
              <p>
                <img src='<%= questionnaire.qimage.url %>'>
              </p>
            <% end %>
          </div>

          <div class='questionnaire-answered'>
            <div class='all-answers'><p>
              回答人数　　<strong><%= questionnaire.answering_users.length %></strong>
            </p></div>
            <div class='bar-caption1' style='bottom: <%= bar_cap_height(questionnaire.answering_a_users.length, questionnaire.answering_b_users.length) %>%;'>
              <strong><%= questionnaire.answering_a_users.length %>人</strong>
            </div>
            <div class='bar-caption2' style='bottom: <%= bar_cap_height(questionnaire.answering_b_users.length, questionnaire.answering_a_users.length) %>%;'>
              <strong><%= questionnaire.answering_b_users.length %>人</strong>
            </div>
            <div class='bar_1' style='height: <%= bar_height(questionnaire.answering_a_users.length, questionnaire.answering_b_users.length) %>%;'></div>
            <div class='bar_2' style='height: <%= bar_height(questionnaire.answering_b_users.length, questionnaire.answering_a_users.length) %>%;'></div>
          </div>

          <div class='questionnaire-options clearfix'>
            <div class='optiona'>
              <p>
                <%= questionnaire.optiona_body %>
              </p>
              <% if questionnaire.optiona_image? %>
              <p>
                <img src='<%= questionnaire.optiona_image.url %>'>
              </p>
              <% end %>
            </div>
            <div class='optionb'>
              <p>
                <%= questionnaire.optionb_body %>
              </p>
              <% if questionnaire.optionb_image? %>
              <p>
                <img src='<%= questionnaire.optionb_image.url %>'>
              </p>
              <% end %>
            </div>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/questionnaires/new.html.erb
<div class="container">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 new-questionnaire">
    <h2>アンケートの作成</h2>
        <%= render 'form', {questionnaire: @questionnaire} %>
    </div>
</div>

app/views/questionnaires/show.html.erb
<div class='container'>
<div class='col-md-offset-2　col-md-8 col-sm-10 col-sm-offset-1 questionnaire-1'>
    <div class='questionnaire-header clearfix'>
      <div class='user-info'>
        <%= image_tag(profile_img_url(@questionnaire.user)) %>
        <%= @questionnaire.user.name %>さんから
      </div>
      <%= render 'users/favorite_form', {questionnaire: @questionnaire} %>
      <div class='questionnaire-static-1'>
        <p><i>回答期限</i></p>
        <% if @questionnaire.date_by? %>
          <p><%= @questionnaire.date_by.strftime("%Y/%m/%d/ %H:%M") %></p>
        <% elsif %>
          <p>なし</p>
        <% end %>
      </div>
    </div>

    <div class='questionnaire-body clearfix'>
      <i class="fa fa-quora" aria-hidden="true"></i>
      <%= @questionnaire.body %>
      <% if @questionnaire.qimage? %>
        <p>
          <img src='<%= @questionnaire.qimage.url %>'>
        </p>
      <% end %>
    </div>

    <div class='questionnaire-answered'>
      <div class='all-answers'><p>
        回答人数　　<strong><%= @questionnaire.answering_users.length %></strong>
      </p></div>
      <div class='bar-caption1' style='bottom: <%= bar_cap_height(@questionnaire.answering_a_users.length, @questionnaire.answering_b_users.length) %>%;'>
        <strong><%= @questionnaire.answering_a_users.length %>人</strong>
      </div>
      <div class='bar-caption2' style='bottom: <%= bar_cap_height(@questionnaire.answering_b_users.length, @questionnaire.answering_a_users.length) %>%;'>
        <strong><%= @questionnaire.answering_b_users.length %>人</strong>
      </div>
      <div class='bar_1' style='height: <%= bar_height(@questionnaire.answering_a_users.length, @questionnaire.answering_b_users.length) %>%;'></div>
      <div class='bar_2' style='height: <%= bar_height(@questionnaire.answering_b_users.length, @questionnaire.answering_a_users.length) %>%;'></div>
    </div>

    <div class='questionnaire-options clearfix'>
      <div class='optiona'>
        <p>
          <%= @questionnaire.optiona_body %>
        </p>
        <% if @questionnaire.optiona_image? %>
        <p>
          <img src='<%= @questionnaire.optiona_image.url %>'>
        </p>
        <% end %>
      </div>
      <div class='optionb'>
        <p>
          <%= @questionnaire.optionb_body %>
        </p>
        <% if @questionnaire.optionb_image? %>
        <p>
          <img src='<%= @questionnaire.optionb_image.url %>'>
        </p>
        <% end %>
      </div>
    </div>

  <div class="answer-btns clearfix">
    <% if @questionnaire.date_by? && Time.current > @questionnaire.date_by %>
      <div class='alert'>
        <p>
          このアンケートの回答は終了しました。
        </p>
      </div>
    <% else %>
    <%= form_for([@questionnaire, @answera]) do |f| %>
      <label class='btn btn-primary answer-btn optiona'>
          <%= f.radio_button :questionnaire_id, @questionnaire.id, {:id => 'a-radio-button', :checked => true} %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <p>Aに回答する</p>
      </label>
    <% end %>
    <%= form_for([@questionnaire, @answerb]) do |f| %>
      <label class='btn btn-primary answer-btn optionb'>
          <%= f.radio_button :questionnaire_id, @questionnaire.id, {:id => 'b-radio-button', :checked => false} %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <p>Bに回答する</p>
      </label>
    <% end %>
    <% if @questionnaire.answering_a_users.include?(current_user) %>
      <%= link_to questionnaire_answera_path(@questionnaire, @questionnaire.answeras.find_by(questionnaire_id: @questionnaire.id, user_id: current_user.id)), method: :delete, data: { confirm: '回答をいったん取り消し、回答し直しますか？' }  do %>
      <input type='button' id='send-edit-a' name='commit' value='回答し直す' class='btn btn-default btn-block'>
      <% end %>
    <% elsif @questionnaire.answering_b_users.include?(current_user) %>
      <%= link_to questionnaire_answerb_path(@questionnaire, @questionnaire.answerbs.find_by(questionnaire_id: @questionnaire.id, user_id: current_user.id)), method: :delete, data: { confirm: '回答をいったん取り消し、回答し直しますか？' }  do %>
      <input type='button' id='send-edit-b' name='commit' value='回答し直す' class='btn btn-default btn-block'>
    <% end %>
    <% else %>
        <input type='button' id='send-submit' name='commit' value='回答' class='btn btn-default btn-block'>
      <% end %>
    <% end %>
  </div>

  <div class='comment-all'>
    <div id="comments_area-<%= @questionnaire.id %>" class='comments-index clearfix'>
      <% if @comments.length > 0 %>
        <%= render partial: 'comments/index', locals: { comments: @comments, questionnaire: @questionnaire } %>
      <% end %>
    </div>
    <hr>
    <div id="new_comment_area-<%= @questionnaire.id %>">
      <%= render partial: 'comments/form', locals: { comment: @comment, questionnaire: @questionnaire } %>
    </div>
  </div>
</div>

<% if @questionnaire.user_id == current_user.id %>
  <div id='new-questionnaire-edit-btn' class='new-questionnaire-btn new-questionnaire-edit-btn'>
      <p>
        <%= link_to edit_questionnaire_path(@questionnaire), data: { confirm: '回答者がまだいない場合にだけ、アンケートを編集できます。回答者がいる場合は新規作成となります。よろしいですか？' }, class: 'in-new-questionnaire-btn' do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
        <% end %>
      </p>
  </div>
  <div id='new-questionnaire-btn' class='new-questionnaire-btn'>
      <p>
        <%= link_to questionnaire_path(@questionnaire), method: :delete, data: { confirm: '本当に削除していいですか？' }, remote: false, class: 'in-new-questionnaire-btn' do %>
          <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
        <% end %>
      </p>
  </div>
<% end %>

app/views/questionnaires/update.html.erb
<h1>Questionnaires#update</h1>
<p>Find me in app/views/questionnaires/update.html.erb</p>