config/routes.rb
Rails.application.routes.draw do
  resources :questionnaires do
    resources :comments
    resources :answeras
    resources :answerbs
    get 'user_posteds', on: :collection
    get 'user_answereds', on: :collection
    get 'user_favorites', on: :collection
  end

  root 'questionnaires#index'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :only => [:index, :show]
  resources :notifications, :only => [:index]
  resources :favorites


  if Rails.env.development? #開発環境の場合
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire_SNS</title>
    <%= csrf_meta_tags %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <script src="https://use.fontawesome.com/4e9a8af73e.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if user_signed_in? %>
      <script>
        var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
          encrypted: true,
          cluster: 'ap1'
        });

        var channel = pusher.subscribe('user_<%= current_user.id %>_channel');
        channel.bind('notification_created', function(data) {
          $('#unread_flag').html(data.unread_flag);
        });
        channel.bind('comment_created', function(data) {
          alert(data.message);
        });
        channel.bind('answered_created', function(data) {
          alert(data.message);
        });
        channel.bind('favorite_created', function(data) {
          alert(data.message);
        });
      </script>
    <% end %>

  </head>

  <body>
    <% if user_signed_in? %>
    <header>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button  type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to questionnaires_path, class: 'navbar-brand' do %>
                      Questionnaire SNS
                    <% end %>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                      <li class="nav-item">
                        <%= link_to questionnaires_path, class: 'nav-link' do %>
                          <i class="fa fa-quora" aria-hidden="true"></i>
                        <% end %>
                      </li>
                      <li class="nav-item">
                        <%= link_to users_path, class: 'nav-link' do %>
                          <i class="fa fa-user-circle" aria-hidden="true"></i>
                        <% end %>
                      </li>
                      <li class="nav-item">
                          <%= link_to notifications_path, class: 'nav-link' do %>
                            <i class="fa fa-bell fa-1x"><span id="unread_flag" class='btn'><%= notification_count(current_user) %></span></i>
                          <% end %>
                      </li>
                      <li class="nav-item">
                        <%= link_to user_path(current_user), class: 'nav-link' do %>
                          <i class="fa fa-address-card" aria-hidden="true"></i>
                        <% end %>
                      </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/layouts/notification_index.html.erb
<div class='container'>
  <section class='comment-notifications'>
    <h2>あなたのアンケートに対するコメントのお知らせ</h2>
    <ul>
      <% @cmtnotifications.each do |cnot| %>
      <hr>
        <li>
          <p>
            あなたのアンケート（<%= link_to "#{cnot.comment.questionnaire.body}", questionnaire_path(cnot.comment.questionnaire, cnotification_id: cnot.id), :target=>["_blank"] %>）にコメントが付きました。
          </p>
          <p><%= cnot.created_at %></p>
        </li>
      <% end %>
    </ul>
  </section>
  <section class='answer-notifications'>
    <h2>あなたのアンケートに対する回答のお知らせ</h2>
    <ul>
      <% @ansnotifications.each do |anot| %>
      <hr>
        <li>
          <p>
            あなたのアンケート（<%= link_to "#{anot.questionnaire.body}", questionnaire_path(anot.questionnaire, anotification_id: anot.id), :target=>["_blank"] %>）に回答が付きました。
          </p>
          <p><%= anot.created_at %></p>
        </li>
      <% end %>
    </ul>
  </section>
</div>